export enum RouteNames {
  // Common
  NotFoundScreen = 'NotFoundScreen',

  // Guest stack
  LoginScreen = 'LoginScreen',
  SignUpScreen = 'SignUpScreen',
  BiometricsVerificationScreen = 'BiometricsVerificationScreen',
  TermsOfUseScreen = 'TermsOfUseScreen',
  PrivacyPolicyScreen = 'PrivacyPolicyScreen',
  EmployerInviteScreen = 'EmployerInviteScreen',
  InviteCodeScreen = 'InviteCodeScreen',
  PasswordLessScreen = 'PasswordLessScreen',
  PasswordLessCompleteScreen = 'PasswordLessCompleteScreen',
  MultiFactorAuthScreen = 'MultiFactorAuthScreen',
  PinAuthScreen = 'PinAuthScreen',
  EmployerSearchScreen = 'EmployerSearchScreen',

  // Onboarding stack
  WelcomeScreen = 'WelcomeScreen',
  OnboardingLinkAccountsScreen = 'OnboardingLinkAccountsScreen',
  OnboardingBudgetInterviewScreen = 'OnboardingBudgetInterviewScreen',
  OnboardingTransactionsSetupScreen = 'OnboardingTransactionsSetupScreen',
  OnboardingBudgetReviewScreen = 'OnboardingBudgetReviewScreen',
  OnboardingEditCashflowBudgetsScreen = 'OnboardingEditCashflowBudgetsScreen',
  OnboardingCompleteScreen = 'OnboardingCompleteScreen',
  IntroductionOnboarding = 'IntroductionOnboarding',
  OnboardingExplainerScreen = 'OnboardingExplainerScreen',
  WelcomeOnboarding = 'WelcomeOnboarding',
  OnboardingTransactionsScreen = 'OnboardingTransactionsScreen',
  OnboardingAddLinkedAccountsScreen = 'OnboardingAddLinkedAccountsScreen',

  // Wellness Login and Onboarding stack
  WellnessWelcomeScreen = 'WellnessWelcomeScreen',
  GoalsSelectorScreen = 'GoalsSelectorScreen',
  GoalsConfirmationScreen = 'GoalsConfirmationScreen',

  // Inner stack
  Home = 'Home',
  Accounts = 'Accounts',
  EditAccountsScreen = 'EditAccountsScreen',
  Cashflow = 'Cashflow',
  BudgetScreen = 'BudgetScreen',
  BudgetDetailsScreen = 'BudgetDetailsScreen',
  ExplainerScreen = 'ExplainerScreen',
  TransactionsScreen = 'TransactionsScreen',
  TransactionDetailsScreen = 'TransactionDetailsScreen',
  EditCashflowBudgetsScreen = 'EditCashflowBudgetsScreen',
  UserSettingsScreen = 'UserSettingsScreen',
  UserProfileScreen = 'UserProfileScreen',
  DeviceSettingsScreen = 'DeviceSettingsScreen',
  BudgetInterviewScreen = 'BudgetInterviewScreen',
  TransactionsSetupScreen = 'TransactionsSetupScreen',
  EditAccountDetailsScreen = 'EditAccountDetailsScreen',
  AddLinkedAccountsScreen = 'AddLinkedAccountsScreen',
  CashflowItemDetailsScreen = 'CashflowItemDetailsScreen',
  LinkAccountsScreen = 'LinkAccountsScreen',
  WebViewContentScreen = 'WebViewContentScreen',
  BudgetReviewScreen = 'BudgetReviewScreen',
  LoggedIn = 'LoggedIn',
  PinSetupScreen = 'PinSetupScreen',
  ActivitiesScreen = 'ActivitiesScreen',
  ArticleActivityScreen = 'ArticleActivityScreen',
  CelebrationScreen = 'CelebrationScreen',
  ActionPlanScreen = 'ActionPlanScreen',
  ActionDetailsScreen = 'ActionDetailsScreen',
  WellnessGoalConfigScreen = 'WellnessGoalConfigScreen',
  PollScreen = 'PollScreen',
  ConfidenceQuestionScreen = 'ConfidenceQuestionScreen',
  QuizActivityScreen = 'QuizActivityScreen',
  VideoActivityScreen = 'VideoActivityScreen',
  GoalDetailsScreen = 'GoalDetailsScreen',
  UpdateSavingsScreen = 'UpdateSavingsScreen',
}
