export { default as ApostaCard } from "./ApostaCard"
export { default as GameCard } from "./GameCard"
export { default as PlayerBubble } from "./PlayerBubble"
export { default as PlayerCard } from "./PlayerCard"
export { default as PlayerOrder } from "./PlayerOrder"
export { default as TableCard } from "./TableCard"
export { default as TrunfoCard } from "./TrunfoCard"
export { default as ResultadoCard } from "./ResultadoCard"
